spring:
  profiles: local

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true

  datasource:
    data: classpath:schema-h2.sql

  devtools:
    remote:
      restart:
        enabled: false
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace











