spring:
  profiles: local

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true

  datasource:
    data: classpath:schema-h2.sql

  devtools:
    remote:
      restart:
        enabled: false

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

